Fixes #34393 - use repoquery format that works on EL7 and EL8
On EL8 repoquery doesn't understand the `nvra` format, leading to the
following error:

    Error: 'Package' object has no attribute 'nvra'

And thus no data reported from that query.
Let's use `%{name}-%{evr}.%{arch}` instead, which is understood by
repoquery on EL7 and EL8.

(cherry picked from commit 8fb44b3f7bf46d0db65435258ffbe5bd7ea75092)